// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiyrsjswxqpvuutpwwzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeXJzanN3eHFwdnV1dHB3d3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODQ3NjAsImV4cCI6MjA1NjE2MDc2MH0.Tm1ADEC1kHmoTNkdjkWjnCjZG2PwjA6617UrUUJhhAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);